const Products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/Airpods_2.jpg', // Place this image in your /public folder
    description: 'Bluetooth technology lets you connect it with compatible devices wirelessly.',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    rating: 4.5,
    numReviews: 12,
    countInStock: 10,
  },
  {
    _id: '2',
    name: 'Sony Alpha a7 III Mirrorless Camera',
    image: '/images/Camera_1.jpg',
    description: 'An advanced 24.2MP Full-frame Image Sensor with 1.8X readout speed.',
    brand: 'Sony',
    category: 'Electronics',
    price: 1999.99,
    rating: 4.0,
    numReviews: 20,
    countInStock: 0,
  },
  {
    _id: '3',
    name: 'iPhone 13 Pro 256GB Memory',
    image: '/images/iphone.jpg',
    description: 'Introducing the iPhone 13 Pro. A dramatically more powerful camera system.',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    rating: 4.0,
    numReviews: 8,
    countInStock: 10,
  },
  {
    _id: '4',
    name: 'Apple Watch Series 7',
    image: '/images/watch_1.jpg',
    description: 'The most durable Apple Watch ever built, with a larger, more advanced display.',
    brand: 'Apple',
    category: 'Electronics',
    price: 399.99,
    rating: 4.0,
    numReviews: 8,
    countInStock: 10,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Optical Gaming Mouse',
    image: '/images/Mouse.jpg',
    description: 'Get better accuracy with the 12,000 DPI optical sensor and customizable RGB lighting.',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    rating: 3.5,
    numReviews: 10,
    countInStock: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/PortableSpeaker.jpg',
    description: 'Meet Echo Dot - Our most popular voice controlled speaker, now with improved sound and a new design.',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    rating: 4.2,
    numReviews: 12,
    countInStock: 10,
  },
];

export default Products;