// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {CartProvider} from './context/CartContext'
import Header from "./Components/Header/Header";
import ReduxProvider from '../store/ReduxProvider.js'
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><ReduxProvider>
        {/* <CartProvider> */}
          
          <Header />
            <main>
          {children}
          <ToastContainer position="top-right" autoClose={3000}/>
        </main>
          
        {/* </CartProvider> */}
        </ReduxProvider>
        
      </body>
    </html>
  );
}
